### ISSUE TITLE
Console spam when tile placed to low

### ISSUE THREAD

**Issue by jokbon** [FearGames/TileCulling#3]
console spam when tile placed to low.
:)

```
[15:27:46 WARN]: java.lang.IllegalArgumentException: y out of range (expected 0-255, got -1)
[15:27:46 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168)
[15:27:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:363)
[15:27:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:80)
[15:27:46 WARN]:        at it.feargames.tileculling.occlusionculling.PaperDataProvider.isOpaqueFullCube(PaperDataProvider.java:48)
[15:27:46 WARN]:        at it.feargames.tileculling.libs.com.logisticscraft.occlusionculling.OcclusionCullingInstance.stepRay(OcclusionCullingInstance.java:333)
[15:27:46 WARN]:        at it.feargames.tileculling.libs.com.logisticscraft.occlusionculling.OcclusionCullingInstance.isVisible(OcclusionCullingInstance.java:289)
[15:27:46 WARN]:        at it.feargames.tileculling.libs.com.logisticscraft.occlusionculling.OcclusionCullingInstance.isVoxelVisible(OcclusionCullingInstance.java:171)
[15:27:46 WARN]:        at it.feargames.tileculling.libs.com.logisticscraft.occlusionculling.OcclusionCullingInstance.isAABBVisible(OcclusionCullingInstance.java:100)
[15:27:46 WARN]:        at it.feargames.tileculling.ChunkTileVisibilityManager.updateVisibility(ChunkTileVisibilityManager.java:64)
[15:27:46 WARN]:        at it.feargames.tileculling.VisibilityUpdateThread.run(VisibilityUpdateThread.java:37)
```

**Comment by sgdc3** [comment]
@jokbon can you reproduce the issue with the latest version please?

**Comment by jokbon** [comment]
This isusue still exist:

https://user-images.githubusercontent.com/29400409/124303729-72446280-db6b-11eb-8c26-7acf56aea1f2.png

**Comment by jokbon** [comment]
to be more precise it spams console when tile culing changes visibility state
