### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by jokbon** [FearGames/TileCulling#4]
```[23:49:39 ERROR]: Error occurred while enabling TileCulling v1.2.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketDataSerializer
        at it.feargames.tileculling.CullingPlugin.onEnable(CullingPlugin.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Purpur-1185]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Purpur-1185]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Purpur-1185]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Purpur-1185]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Purpur-1185]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:644) ~[patched_1.17.jar:git-Purpur-1185]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[patched_1.17.jar:git-Purpur-1185]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[patched_1.17.jar:git-Purpur-1185]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.jar:git-Purpur-1185]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R3.PacketDataSerializer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Purpur-1185]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Purpur-1185]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more```

**Comment by sgdc3** [comment]
Done, let me know if it works as intended:
https://ci.codemc.io/view/All/job/FearGames/job/TileCulling/

**Comment by jokbon** [comment]
works

**Comment by sgdc3** [comment]
Thank you
